#!/usr/bin/bash
#swww init
swww img $1 --transition-type grow --transition-pos "$(hyprctl cursorpos)" --invert-y --transition-duration 3 &
wal -i $1 -n --saturate 0.5 --backend colorz -o $HOME/.local/bin/updatetheme &
