#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
swaync &

# waybar
$HOME/.config/waybar/startup &

# wallpaper
# $scripts/wall "$(< "${HOME}/.cache/wal/wal")" &


# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
