# Shell variables
# Generated by 'wal'
wallpaper='/home/lee/.config/hypr/wallpapers/1319547.png'

# Special
background='#221919'
foreground='#c7c5c5'
cursor='#c7c5c5'

# Colors
color0='#221919'
color1='#ca6360'
color2='#4cc35c'
color3='#4eaec4'
color4='#4285c0'
color5='#92b8da'
color6='#6b9acd'
color7='#c7c5c5'
color8='#595252'
color9='#ca6360'
color10='#4cc35c'
color11='#4eaec4'
color12='#4285c0'
color13='#92b8da'
color14='#6b9acd'
color15='#c7c5c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
