--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lee/.config/hypr/wallpapers/6.jpg"

-- Special
background="#23110f"
foreground="#c8c3c3"
cursor="#c8c3c3"

-- Colors
color0="#23110f"
color1="#c04e41"
color2="#3fb7bc"
color3="#3a63ae"
color4="#6a51c5"
color5="#ca61c1"
color6="#c85959"
color7="#c8c3c3"
color8="#5a4c4b"
color9="#c04e41"
color10="#3fb7bc"
color11="#3a63ae"
color12="#6a51c5"
color13="#ca61c1"
color14="#c85959"
color15="#c8c3c3"
