# Shell variables
# Generated by 'wal'
wallpaper='/home/lee/.config/hypr/wallpapers/6.jpg'

# Special
background='#23110f'
foreground='#c8c3c3'
cursor='#c8c3c3'

# Colors
color0='#23110f'
color1='#c04e41'
color2='#3fb7bc'
color3='#3a63ae'
color4='#6a51c5'
color5='#ca61c1'
color6='#c85959'
color7='#c8c3c3'
color8='#5a4c4b'
color9='#c04e41'
color10='#3fb7bc'
color11='#3a63ae'
color12='#6a51c5'
color13='#ca61c1'
color14='#c85959'
color15='#c8c3c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
